### ISSUE TITLE
WHID-Elite keeps connecting/disconnecting from Windows

### ISSUE THREAD

**Issue by knifebright** [whid-injector/whid-31337#10]
After a successful test during a few minutes, with a fully charged battery and a live connection to a PC, I tried WHID-Elite on a different computer to demonstrate it. It kept connecting and disconnecting from Windows (you could ear the respective sounds). Changed to a new USB port, and the same kept happening. Tried it later on the first computer and it never worked again.

It has a SIM card that used to work and the LiPo battery connected (LP584070 3.7V/1500mAh)

![imagem](https://user-images.githubusercontent.com/44803381/74343829-9a2efc80-4da3-11ea-8bc2-73dfb9b456ad.png)

**Comment by whid-injector** [comment]
https://github.com/whid-injector/whid-31337#how-to-report-bugs

https://github.com/whid-injector/whid-31337#troubleshooting-bootloops 
Most of the times is either the laptop USB3.0 controller (try use an usb HUB 2.0) to narrow that if that is the issue.
Or also the LiPo battery. (have u ever run the whidelite WITHOUT LiPo? That may damage the board as expressively stated in the WIKI)
Then there may be other corner cases stated in the URL above.

https://github.com/whid-injector/whid-31337#hardware-unbrick--hard-reset

**Comment by knifebright** [comment]
OK!
Connected through a USB 2.0 Hub and it is working.
Thanks
