### ISSUE TITLE
AT Error

### ISSUE THREAD

**Issue by cyb3rr0nn13** [whid-injector/whid-31337#13]
Hi....
i bought a [thingsmobile SIM](https://www.thingsmobile.com/), and a [WHiD-31337](https://github.com/whid-injector/whid-31337).

When I installed everything with the [Arduino IDE](https://arduino.cc) so far and 
tried to address the FONA SIM800l via AT Serial Monitor, 
i received the following error message:

23:58:23.583 -> FONA basic test
23:58:23.583 -> Initializing....(May take 3 seconds)
23:58:23.682 -> Attempting to open comm with ATs
23:58:23.754 -> 	---> AT
23:58:23.754 -> 	<--- AT
23:58:23.798 -> 	---> AT
23:58:23.798 -> 	<--- AT
23:58:23.855 -> 	---> ATE0
23:58:23.916 -> 	<--- ATE0
23:58:24.008 -> 	---> ATE0
23:58:24.008 -> 	<--- OK
23:58:24.105 -> 	---> AT+CVHU=0
23:58:24.105 -> 	<--- OK
23:58:24.227 -> 	---> ATI
23:58:24.720 -> 	<--- SIM800 R14.18
23:58:24.720 -> 
23:58:24.720 -> OK
23:58:24.720 -> 
23:58:24.800 -> 	---> AT+CPMS="SM","SM","SM"
23:58:24.886 -> 	<--- +CPMS: 0,10,0,10,0,10
23:58:24.886 -> FONA is OK
23:58:24.886 -> Found ???
23:58:25.075 -> 
23:58:25.075 -> FONA> t
00:00:22.660 -> 	---> AT+CCLK?
00:00:32.813 -> 	<--- 
00:00:32.813 -> Time = ⸮⸮⸮R⸮4⸮⸮RL⸮⸮⸮Թ⸮⸮⸮>⸮dy
00:00:32.813 -> ⸮2⸮!⸮⸮xrE⸮⸮⸮3C⸮!⸮O⸮y⸮⸮⸮t⸮⸮⸮
00:00:32.813 -> Q⸮
00:00:32.813 -> ιC⸮⸮zȀ⸮⸮Q⸮⸮⸮⸮#r⸮!⸮⸮A⸮,z⸮⸮⸮8-⸮⸮;⸮&,⸮pp⸮⸮⸮⸮dY⸮⸮и)⸮⸮s⸮⸮S⸮⸮
00:00:32.813 -> y
00:00:32.813 -> FONA>

WTF ?! 
What's that? 
And does anyone know how to fix that? 
Thank you very much!

**Comment by whid-injector** [comment]
What do you mean with:"tried to address the FONA SIM800l via AT Serial Monitor,"?

1) The README is quite exaustive on how to use it and what the sketches are doing
2) Be more precise. 
3) Did you read carefully the entire README? Lipo is charged?
4) https://github.com/whid-injector/whid-31337#how-to-report-bugs

**Comment by cyb3rr0nn13** [comment]
I mean , if i type `?` in serial monitor,  sometimes it responds with `FONA is ready`...and sometimes even not

**Comment by whid-injector** [comment]
Which firmware/sketch did u flash?

**Comment by whid-injector** [comment]
https://www.youtube.com/watch?v=X6BXdqhLbCg
Did you follow this? 
What speed u set the serial monitor? 9600bps?

**Comment by cyb3rr0nn13** [comment]
I used the AT testing fw....and yes, i tried 9600 and 115200 as well...both the same...

**Comment by whid-injector** [comment]
Ok. Now to help you I need as many detailed information as possible:
This https://github.com/whid-injector/whid-31337#how-to-report-bugs
And also...
1) Did u try this sketch? https://github.com/whid-injector/whid-31337/tree/master/WHID_Elite_v.1.3.1
2) The simcard has a pincode or doesn't require it?
3) Did you try another simcard? 
4) Do u have connected a Lipo right? did u fully charge it? How many mAh is it? 

Overall this to me looks like a problem with different baudrate set on the monitor. Is the UBS port a 3.0? Which OS?
```
00:00:22.660 -> ---> AT+CCLK?
00:00:32.813 -> <---
00:00:32.813 -> Time = ⸮�⸮⸮R⸮4⸮⸮�RL⸮�⸮⸮Թ⸮⸮⸮>⸮dy
00:00:32.813 -> ⸮2⸮!⸮⸮�xr�E�⸮�⸮⸮3C⸮!⸮O⸮y⸮⸮��⸮t⸮�⸮⸮
00:00:32.813 -> Q⸮
00:00:32.813 -> ιC⸮⸮zȀ⸮�⸮Q⸮⸮⸮⸮#r⸮!⸮⸮A⸮,z⸮⸮⸮8-⸮��⸮;⸮&,⸮pp⸮⸮⸮⸮�dY��⸮⸮и)⸮⸮s⸮⸮S⸮�⸮
```

**Comment by cyb3rr0nn13** [comment]
1. Yes, i tried....but with the mainsketch it freezes @ AT

2. Yes, SIM has PIN lock

3. Nope

4. Fully charged...i believe round about 1200mAh

OS is the latest Raspbian or Up2Date Win10 on lattepanda

**Comment by minkione** [comment]
1) disable the pincode and try again
2) try also another sincard (witth pincode disabled)
3) try the main sketch (if u wanna use the pincode) u have to place it in the sketch before flashing it. https://github.com/whid-injector/whid-31337/blob/ee4b2216aa9026017998e8223cfdb44b3118b819/WHID_Elite_v.1.3.1/WHID_Elite_v.1.3.1.ino#L566

If the problem is the pincode... Please try add that line into the Testsuite sketch. 

I think the TestSuite doesn't have that one.

**Comment by minkione** [comment]
Rule of thumb. For testing always disable pincodes. ;)

**Comment by cyb3rr0nn13** [comment]
@minkione i tried out your recommended sketch.....
heres the AT log

01:47:02.840 -> 	---> AT
01:47:03.341 -> 	<--- 
01:47:03.374 -> 	---> AT
01:47:03.408 -> 	<--- AT
01:47:03.441 -> 	---> ATE0
01:47:03.507 -> 	<--- ATE0
01:47:03.640 -> 	---> ATE0
01:47:03.673 -> 	<--- OK
01:47:03.706 -> 	---> AT+CVHU=0
01:47:03.773 -> 	<--- OK
01:47:03.905 -> 	---> ATI
01:47:04.404 -> 	<--- SIM800 R14.18
01:47:04.404 -> 
01:47:04.404 -> OK
01:47:04.404 -> 
01:47:04.404 -> +CPIN: READY
01:47:04.404 -> 
01:47:04.438 -> 	---> AT+CPMS="SM","SM","SM"
01:47:04.537 -> 	<--- ERROR
01:47:04.571 -> 	---> AT+CPIN=1234
01:47:04.637 -> 	<--- ERROR
01:47:06.164 -> 	---> AT+CMGF=1
01:47:06.231 -> 	<--- OK
01:47:06.264 -> 	---> AT+CPMS?
01:47:06.363 -> 	<--- +CPMS: "SM",0,10,"SM",0,10,"SM",0,10
01:47:06.397 -> Number of SMS: 0
01:47:06.397 -> 
01:47:06.397 -> 
Deleting SMS...
01:47:06.928 -> 	---> AT+CMGDA="DEL ALL"
01:47:06.928 -> 
01:47:06.995 -> 	<--- OK
01:47:06.995 -> WHID Elite 1.3.1 is OK

Whats the syntax to execute successfully code via a SMS?

**Comment by cyb3rr0nn13** [comment]
Ok, i got it now :)

06:13:03.529 -> FONA> 
06:13:03.717 -> SMS Ready
06:13:14.876 -> t
06:13:14.936 -> 	---> AT+CCLK?
06:13:15.030 -> 	<--- +CCLK: "04/01/01,01:27:08+00"
06:13:15.030 -> Time = "04/01/01,01:27:08+00"

But how do i execute for example a serial exfiltration via sms command?
How has this sms to look like?

**Comment by minkione** [comment]
See. Was the missing pincode on the sketch...

Regardingthe other question... Have u read the documentation and watched the videos on youtube I spent hours making?! 

Come on folks... RTFM!!!

**Comment by cyb3rr0nn13** [comment]
![rtfm](https://user-images.githubusercontent.com/60270666/88134208-4cd17980-cbe4-11ea-8162-072f442590f0.jpg)
