### ISSUE TITLE
Questions about China SIM card

### ISSUE THREAD

**Issue by fusss9** [whid-injector/whid-31337#4]
Maybe my SIM card does not support 2G. I also asked the April brothers, they said to use the China Mobile Card.
![QQ图片20191124093647](https://user-images.githubusercontent.com/30801524/69487979-a8edcd80-0e9e-11ea-9960-6c927aa4296b.png)

**Comment by whid-injector** [comment]
This is not the way an issue is created...

**Comment by whid-injector** [comment]
If already got the answer by manufacturer... why even opening the issue?
