### ISSUE TITLE
Test Suite Fails to Make Calls with US Numbers

### ISSUE THREAD

**Issue by michael-bey** [whid-injector/whid-31337#6]
If you are using the test image to make phone calls, it will not be successful using Arduino Sketch and a US phone number. The Serial Monitor is expecting a certain amount of characters (See https://github.com/benichmt1/whid-31337/blob/master/WHIDElite_TestSuite_v.1.1/WHIDElite_TestSuite_v.1.1.ino#L494) before it will dial.

I was able to hack it this by changing the number to 11 (https://github.com/benichmt1/whid-31337/blob/master/WHIDElite_TestSuite_v.1.1/WHIDElite_TestSuite_v.1.1.ino#L497), but I think a more robust way would be inserting a new line so the console knows it's finished.

Something like `pcSerial.printf("\r\n");` might work OK. I will test shortly unless you have a different idea to fix the issue.

**Comment by minkione** [comment]
Hi,
- Out of curiosity, which MNO are you using in US? Ting?
- I have just tested the TestSuite with my own phone number (13 digits) and it worked perfectly.

![whid testsuite](https://user-images.githubusercontent.com/25242404/71290407-6ec9fb80-2378-11ea-99a9-47c566d45f5d.png)
![phone](https://user-images.githubusercontent.com/25242404/71290411-725d8280-2378-11ea-80b4-71e88b21d8e5.jpg)

The buffer just allocates enough space to be able to handle all phone numbers until 30 digits.
An US callerID should not be more than 30 digits. 

So far, I cannot replicate your issue.
Are you using the Arduino SerialMonitor as terminal? Putty? Minicom?

Try send an SMS spy:00xxxxxxxxxxxxxxxx  command after flashing the WHID_Elite_v.1.3.1 sketch. Wonder if that works or not.

**Comment by minkione** [comment]
I just tried with Putty... and I noticed that terminal is acting differently respect the Serial Monitor embedded in Arduino.
Might be related to some special encoding, chart termination, or similar stuff.
Try using the Serial Monitor in Arduino and check if it works then.
![Screenshot 2019-12-20 at 22 41 18](https://user-images.githubusercontent.com/25242404/71290964-de8cb600-2379-11ea-97f3-b7eda0e4ea31.png)

**Comment by minkione** [comment]
Maybe some configurations like this?
https://forum.arduino.cc/index.php?topic=601718.0

**Comment by michael-bey** [comment]
Interestingly enough I was using the serial monitor. I would type in the phone number and press "send" but it wouldn't actually send until the text reached 30 characters. That's why I edited mine to have a specific limit. I will try in a regular Putty console and report back.

**Comment by minkione** [comment]
Closing for now, since it was not possible to replicate the issue and anyway is a FONA library problem.
